# Generated by Django 3.2.8 on 2021-10-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='categoia',
            new_name='categoria',
        ),
    ]
